<section class="container">
	<div class="maps-container">
    	<h2>Re-Packing Locations</h2>
        <img src="http://clifference.com/wp-content/uploads/2013/05/google-maps.jpg" 
        style="margin: 10px 0;width: 100%;" />
    </div>
    <div class="filters">
    	<div class="icons">
        	&nbsp;
        </div>
        <div class="options">
        	<h3>CARRIER</h3>
            <div class="group">
            	<input type="checkbox"> LBC
            </div>
            <div class="group">
            	<input type="checkbox"> Xend
            </div>
        </div>
        <div class="actions">
        	<a href="" class="donate">Donation Form</a>
        </div>
    </div>
</section>