<section class="carousel">
    <div class="frame">
        <div class="item">
            <img src="/assets/images/banner/banner-1.jpg" />
        </div>
    </div>
</section>
<section class="homepage-wrapper">
	<section class="container">
        <h4 class="slogan clearfix">
            <div class="line left-line pull-left">&nbsp;</div>
            <span>GREAT WAYS TO</span>
            <div class="line right-line pull-left">&nbsp;</div>
        </h4>
        <h2>RAISE MONEY FOR YOUR CAUSE</h2>
        <h6>
        	CREATE YOUR OWN FUNDRAISER OR JOIN AN EXISTING FUNDRAISING TEAM 
            WHICH ONE IS RIGHT FOR YOU?
        </h6>
        
        <div class="places clearfix">
        <?php for($x = 1; $x<=6; $x++) : ?>
        	<div class="item">
            	<div class="content">
                    <h3>Tacloban City</h3>
                    <img src="/assets/images/places/tacloban-city.jpg" />
                    <p>
                        Neque porro quisquam est qui dolorem ipsum quia dolor 
                        sit amet, consectetur, adipisci velit.
                    </p>
                </div>
            </div>
        <?php endfor; ?>
        </div>
        
        <div class="note">
        	<p>
            	Neque porro quisquam est qui dolorem ipsum quia dolor 
                sit amet, consectetur, adipisci velit.
            </p>        
        </div>
	</section>
</section>